### ISSUE TITLE
Decoding gltf file run-time errors in Windows 10

### ISSUE THREAD

**Issue by Edwardhk** [decisionforce/pgdrive#251] opened 2021-02-08 03:10 UTC
### Problem
It fails to decode the `assets/models/new/130/scene.gltf` and terminate the program due to runtime error.

I have tried a fresh install on both win10 and linux twice, and it works seamlessly with the latter, so I assumed the errors is caused by win10 with the encoding of this specific gltf file.

This error happens occasionally, sometimes the program will be able to finish the whole/half episode.

Is there anyway to load this file in `utf-8` or `binary mode`?

### My environment setup
OS: Windows 10
Python version: 3.7 (via Anaconda)

### Step to reproduce
```
python -m pgdrive.examples.enjoy_expert
```

### Error messages
First error
```
Traceback (most recent call last):
  File "<PATH>.conda\envs\rl_dev\lib\site-packages\gltf\converter.py", line 1819, in load_model
    convert(file_path, bamfilepath, gltf_settings)
  File "<PATH>.conda\envs\rl_dev\lib\site-packages\gltf\converter.py", line 1796, in convert
    gltf_data = json.load(gltf_file)
  File "<PATH>.conda\envs\rl_dev\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'cp950' codec can't decode byte 0x8d in position 49100: illegal multibyte sequence
```

Second error (caused by the first error)
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<PATH>\.conda\envs\rl_dev\lib\site-packages\gltf\loader.py", line 21, in load_file
    options=options
  File "<PATH>\.conda\envs\rl_dev\lib\site-packages\gltf\converter.py", line 1825, in load_model
    raise RuntimeError("Failed to convert glTF file")
RuntimeError: Failed to convert glTF file
:loader(error): Loading scene.gltf failed with RuntimeError exception.
:loader(error): Couldn't load file pgdrive/assets/models/new/130/scene.gltf: invalid.
```

**Comment by lqy0057** [comment] 2021-02-08 08:26
Hi, Edwardhk. Thanks for your feedback, and I am trying to reproduce this problem on my Win10 machine. I will let you know if there is any progress

**Comment by lqy0057** [comment] 2021-02-14 03:54
Hmm, I can not reproduce this error on my Win10 laptop. But, this is definitely caused by the character encoding. On Linux and MacOS, UTF-8 is the default encoding when running Python, but on Windows, the character encoding is the same as your environment variable. There is good news that the default encoding of Python3.9 is UTF-8, no matter what platform it is.
So we recommend to:
- Set the environment variable to UTF-8, by ```set PYTHONIOENCODING=utf-8``` in your terminal.
- Update to Python3.9 (But we don't test PGDrive with it)
- Run PGDrive on your linux machine

Since this error is reported in a third-party library, it is difficult to modify its source code. We are discussing a clean way to set the default encoding to UTF-8 in the ```open() ``` function.

**Comment by pengzhenghao** [comment] 2021-02-14 05:04
Can we set the environment variable to the required one when importing the pgdrive? Within python, like os.environ[xxx]

Best regards!

Peng Zhenghao (彭正皓)

**Comment by lqy0057** [comment] 2021-02-14 05:36
```os.environ["PYTHONUTF8"] = "on"``` may work, but I am not sure. No matter whether it works or not, I will add it to os.environ in the next PGDrive edition to do a double-check.

**Comment by gamecraftCZ** [comment] 2021-02-21 21:46
You can change Windows  encoding to UTF8 systemwide. This works for me. ;)
![image](https://user-images.githubusercontent.com/11137519/108639791-a198e380-7496-11eb-9beb-713a585e7529.png)

**Comment by pengzhenghao** [comment] 2021-02-22 03:17
> You can change Windows encoding to UTF8 systemwide. This works for me. ;)
> ![image](https://user-images.githubusercontent.com/11137519/108639791-a198e380-7496-11eb-9beb-713a585e7529.png)

Hi @gamecraftCZ ! Thank for your help!

Do you have any suggestion for PGDrive to accommodate those users who might not wish to turn on this option?

Thanks!

**Comment by pengzhenghao** [comment] 2021-02-22 04:39
Thank you Patrik!

Do you have any suggestion on what should we do in PGDrive to help the user who might not want to turn on this option? Thanks!

Best regards!

Peng Zhenghao (彭正皓)

**Comment by gamecraftCZ** [comment] 2021-02-25 17:05
1. Maybe panda3d may have support for setting fixed encoding. But I never worked with with it so I don't know.
2. If not, we can as a workaround have the files also have in encoding for windows and load them if windows is detected. But I don't like this option.

**Comment by pengzhenghao** [comment] 2021-02-26 00:37
> * Maybe panda3d may have support for setting fixed encoding. But I never worked with with it so I don't know.
> * If not, we can as a workaround have the files also have in encoding for windows and load them if windows is detected. But I don't like this option.

Great! Thanks for you suggestions! Close this issue temporarily.

**Closed by pengzhenghao** 2021-02-26 00:37 UTC
Labels: question
